[pytest]
addopts = -s --slowmo 1000
markers =
    smoke: vital core functionality
    regression: full feature verification
    e2e: end-to-end user flows
    integration: api testing between services: front-back